version: "3.3"
services:
  cryptopia_api:
    build: .
    ports:
      - "3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on: 
      - cryptopia_db
    command: sh -c "yarn && yarn run dev"
  cryptopia_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:

